// Selecting a specific subset of columns
Colors = SELECTCOLUMNS (
    VALUES ( 'Product'[Color]),
    "Color", 'Product'[Color],
    "Products", CALCULATE ( COUNTROWS ('Product')),
    "Sales Amount", [Sales Amount]
)
Date of Max :=
VAR DailySales =
    ADDCOLUMNS (
        VALUES ('Date'[Date]),
        "Daily Sales", [Sales Amount]
    )
VAR MaxDailySales = MAXX  (DailySales, [Daily Sales])
VAR DatesWithMax =
    SELECTCOLUMNS (
        FILTER (
            DailySales,
            [DailySales] = MaxDailySales
        )
    )
// Using AVG to smooth sales
AvgXSales30 :=
VAR LastVisibleDate = MAX ( 'Date'[Date])
VAR NumberOfDays = 30
VAR PeriodToUse =
    FILTER (
        ALL ('Date'),
        AND (
            'Date'[Date] > LastVisibleDate - NumberOfDays,
            'Date'[Date] <= LastVisibleDate
        )
    )
VAR Result = 
    CALCULATE (
        AVERAGEX ( 'Date', [Sales Amount]),
        PeriodToUse
    )
RETURN Result
// AVERAGEX ignores blank rows
//Other version considering blank rows
AvgXSales30 :=
VAR LastVisibleDate = MAX ( 'Date'[Date])
VAR NumberOfDays = 30
VAR PeriodToUse =
    FILTER (
        ALL ('Date'),
        AND (
            'Date'[Date] > LastVisibleDate - NumberOfDays,
            'Date'[Date] <= LastVisibleDate
        )
    )
VAR Result =
CALCULATE (
    DIVIDE (
        [Sales Amount],
        COUNTROWS ('Date')
    ),
    PeriodToUse
)
RETURN 
    Result
// Using RANKX
Rank Cat on Sales :=
RANKX (
    ALL ('Product'[Category]),
    [Sales Amount]
)
// Rankx steps:
//1. Builds a lookup 
//table by iterating over the table provided as the first parameter.
// During the iteration it evaluated its second parameter in the row context of
// the iteration. At the end it sorts the lookup table.
// Other example
Rounded Sales := MROUND ([Sales Amount], 1000000)
Rank On Rounded Sales :=
RANKX (
    ALL ( 'Product'[Brand]),
    [Rounded Sales]
)
Rank On Rounded Sales Dense :=
RANKX (
    ALL ( 'Product'[Brand]),
    [Rounded Sales],
    ,
    ,
    DENSE
)