PY YTD Sales :=
CALCULATE (
    [Sales Amount],
    DATESYTD ( SAMEPERIODLASTYEAR ('Date'[Date]))
)
YOY YTD Sales :=
VAR CyYtdSales = [YTD Sales]
VAR PyYtdSales = [PY YTD Sales]
VAR YoyYtdSales =
    IF (
        NOT ISBLANK (CyYtdSales) && NOT ISBLANK (PyYtdSales),
        CyYtdSales - PyYtdSales
    )
RETURN
    YoyYtdSales
// LASTDATE is like MAX but returns a table. 
MAT Sales :=
CALCULATE (
    [Sales Amount],
    DATESINPERIOD (
        'Date'[Date],
        MAX ( 'Date'[Date]),
        -1,
        YEAR
    )
)
// second version for MAT Sales
MAT Sales v2 :=
CALCULATE (
    [Sales Amount],
    DATESBETWEEN (
        'Date'[Date],
        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE('Date'[Date]))),
        LASTDATE ('Date'[Date])
    )
)
// DATESBETWEEN works at day level
MAA Sales :=
CALCULATE (
    DIVIDE (
        [Sales Amount],
        DISTINCTCOUNT('Date'[Date])
    ),
    DATESINPERIOD (
        'Date'[Date],
        MAX ( 'Date'[Date]),
        -1, 
        YEAR
    )
)
// Last balance by using LASTDATE to overwrite the filter context on Date:
LastBalance :=
CALCULATE (
    SUM ( Balances[Balance] ),
    LASTDATE ( 'Date'[Date] )
)
// LASTNONBLANK is an iterator that scans a table and returns the last value of the table for which the second parameter does not evaluate to BLANK
LastBalanceNonBlank :=
CALCULATE (
    SUM (
        LASTNONBLANK (
            'Date'[Date],
            COUNTROWS ( RELATEDTABLE (Balances))
        )
    )
)
// Correct version of the 2 previous examples:
LastBalanceAllCustomers :=
VAR LastDateAllCustomers =+
    CALCULATETABLE (
        LASTNONBLANK (
            'Date'[Date],
            COUNTROWS (RELATEDTABLE (Balances))
        ),
        ALL ( Balances[Balance])
    )
VAR Result =
    CALCULATE (
        SUM ( Balances[Balance] ),
        LastDateAllCustomers
    )
RETURN
    Result
// Second version using nested iterators
LastBalanceIndividualCustomer :=
SUMX (
    VALUES ( Balances[Name]),
    CALCULATE (
        SUM ( Balances[Balance]),
        LASTNONBLANK (
            'Date'[Date],
            COUNTROWS ( RELATEDTABLE (Balances))
        )
    )
)